"use client";

/* Generated by tools/build-react-icons.py from docs/icons.html — do not edit.
   59 glyphs. To add one, put it in the docs first and re-run the script. */

import { forwardRef, type SVGProps } from "react";
import { cn } from "./cn";

export const iconNames = [
  "arrow-up-right",
  "backward",
  "bell",
  "bolt",
  "bookmark",
  "calendar",
  "camera",
  "check",
  "chevron-down",
  "chevron-left",
  "chevron-right",
  "chevron-up",
  "clock",
  "close",
  "doc",
  "download",
  "drop",
  "filter",
  "flame",
  "folder",
  "forward",
  "garage",
  "gear",
  "grid",
  "heart",
  "house",
  "info",
  "lightbulb",
  "link",
  "lock",
  "mail",
  "message",
  "mic",
  "moon-stars",
  "music-note",
  "newspaper",
  "pause",
  "pencil",
  "people",
  "person",
  "photo",
  "pin",
  "play",
  "plus",
  "refresh",
  "repeat",
  "search",
  "send",
  "share",
  "shield",
  "sliders",
  "sparkles",
  "speaker",
  "star",
  "sun",
  "trash",
  "warning",
  "waveform",
  "wifi",
] as const;

export type IconName = (typeof iconNames)[number];

const GLYPHS: Record<IconName, JSX.Element> = {
  "arrow-up-right": <><path d="M6 14 14 6M7.5 6H14v6.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></>,
  "backward": <><path d="M5.5 4.5v11" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round"/><path d="M15 5.6v8.8a.6.6 0 0 1-.93.5L7.6 10.5a.6.6 0 0 1 0-1l6.47-4.4a.6.6 0 0 1 .93.5Z" fill="currentColor"/></>,
  "bell": <><path d="M10 3.5A4.5 4.5 0 0 1 14.5 8c0 3 1 4 1.5 4.5H4c.5-.5 1.5-1.5 1.5-4.5A4.5 4.5 0 0 1 10 3.5Z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"/><path d="M8.5 15.5a1.6 1.6 0 0 0 3 0" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/></>,
  "bolt": <><path d="M11 3 5 11h4l-1 6 6-8h-4l1-6Z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"/></>,
  "bookmark": <><path d="M5.5 5A1.5 1.5 0 0 1 7 3.5h6A1.5 1.5 0 0 1 14.5 5v11.5L10 13l-4.5 3.5V5Z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"/></>,
  "calendar": <><rect x="3.5" y="4.5" width="13" height="12" rx="2" stroke="currentColor" strokeWidth="1.5"/><path d="M7 3v3M13 3v3M3.5 8.5h13" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/></>,
  "camera": <><path d="M3.5 7A1.5 1.5 0 0 1 5 5.5h1.5L8 3.5h4l1.5 2H15A1.5 1.5 0 0 1 16.5 7v7a1.5 1.5 0 0 1-1.5 1.5H5A1.5 1.5 0 0 1 3.5 14V7Z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"/><circle cx="10" cy="10.5" r="2.8" stroke="currentColor" strokeWidth="1.5"/></>,
  "check": <><path d="M4 10.5 8.5 15 16 5.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></>,
  "chevron-down": <><path d="m5 8 5 5 5-5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></>,
  "chevron-left": <><path d="M12 5l-5 5 5 5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></>,
  "chevron-right": <><path d="m8 5 5 5-5 5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></>,
  "chevron-up": <><path d="m5 12 5-5 5 5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></>,
  "clock": <><circle cx="10" cy="10" r="6.5" stroke="currentColor" strokeWidth="1.5"/><path d="M10 6.5V10l2.5 2" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></>,
  "close": <><path d="m5 5 10 10M15 5 5 15" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/></>,
  "doc": <><path d="M5.5 3.5h6L15 7v9.5H5.5V3.5Z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"/><path d="M11.5 3.5V7H15M8 10.5h4M8 13h4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></>,
  "download": <><path d="M10 3.5v9M6.5 9.5l3.5 3 3.5-3M4 16.5h12" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></>,
  "drop": <><path d="M10 2.8C7.7 6 5.5 8.6 5.5 11.4a4.5 4.5 0 0 0 9 0c0-2.8-2.2-5.4-4.5-8.6Z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"/></>,
  "filter": <><path d="M3.5 5.5h13M6 10h8M8.5 14.5h3" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/></>,
  "flame": <><path d="M10 3c-2.5 3-4.5 5.2-4.5 7.4a4.5 4.5 0 0 0 9 0C14.5 8.2 12.5 6 10 3Z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"/></>,
  "folder": <><path d="M3.5 5.5A1.5 1.5 0 0 1 5 4h3l1.5 2H15a1.5 1.5 0 0 1 1.5 1.5V14a1.5 1.5 0 0 1-1.5 1.5H5A1.5 1.5 0 0 1 3.5 14V5.5Z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"/></>,
  "forward": <><path d="M14.5 4.5v11" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round"/><path d="M5 5.6v8.8a.6.6 0 0 0 .93.5l6.47-4.4a.6.6 0 0 0 0-1L5.93 5.1a.6.6 0 0 0-.93.5Z" fill="currentColor"/></>,
  "garage": <><path d="M3 9.5 10 4l7 5.5M5 8.5V16h10V8.5M7 11h6M7 13.5h6" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></>,
  "gear": <><circle cx="10" cy="10" r="2.5" stroke="currentColor" strokeWidth="1.5"/><path d="M10 2.5v3M10 14.5v3M2.5 10h3M14.5 10h3M4.7 4.7l2.1 2.1M13.2 13.2l2.1 2.1M15.3 4.7l-2.1 2.1M6.8 13.2l-2.1 2.1" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round"/></>,
  "grid": <><rect x="3.5" y="3.5" width="5.5" height="5.5" rx="1.5" stroke="currentColor" strokeWidth="1.5"/><rect x="11" y="3.5" width="5.5" height="5.5" rx="1.5" stroke="currentColor" strokeWidth="1.5"/><rect x="3.5" y="11" width="5.5" height="5.5" rx="1.5" stroke="currentColor" strokeWidth="1.5"/><rect x="11" y="11" width="5.5" height="5.5" rx="1.5" stroke="currentColor" strokeWidth="1.5"/></>,
  "heart": <><path d="M10 16.5S3.5 12.5 3.5 8.2A3.6 3.6 0 0 1 10 6a3.6 3.6 0 0 1 6.5 2.2c0 4.3-6.5 8.3-6.5 8.3Z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"/></>,
  "house": <><path d="M3 9.5 10 4l7 5.5M5 8.5V16h10V8.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></>,
  "info": <><circle cx="10" cy="10" r="6.5" stroke="currentColor" strokeWidth="1.5"/><path d="M10 9v4M10 6.4h.01" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/></>,
  "lightbulb": <><path d="M10 3a5 5 0 0 0-2.5 9.3V14a1 1 0 0 0 1 1h3a1 1 0 0 0 1-1v-1.7A5 5 0 0 0 10 3ZM8.5 17h3" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></>,
  "link": <><path d="M8.5 11.5a3 3 0 0 0 4.2 0l2.5-2.5a3 3 0 1 0-4.2-4.2l-1 1M11.5 8.5a3 3 0 0 0-4.2 0L4.8 11a3 3 0 1 0 4.2 4.2l1-1" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/></>,
  "lock": <><rect x="5" y="9" width="10" height="7" rx="2" stroke="currentColor" strokeWidth="1.5"/><path d="M7 9V6.5a3 3 0 0 1 6 0V9" stroke="currentColor" strokeWidth="1.5"/></>,
  "mail": <><rect x="3" y="4.5" width="14" height="11" rx="2" stroke="currentColor" strokeWidth="1.5"/><path d="m4.5 7 5.5 4 5.5-4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></>,
  "message": <><path d="M5.5 4h9a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2H8.5l-3 3v-3a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"/></>,
  "mic": <><rect x="7.5" y="3.5" width="5" height="9" rx="2.5" stroke="currentColor" strokeWidth="1.5"/><path d="M5.5 10a4.5 4.5 0 0 0 9 0M10 14.5v2" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/></>,
  "moon-stars": <><path d="M14.5 12.5A6 6 0 0 1 7.5 5.5 6 6 0 1 0 14.5 12.5Z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"/><path d="m14 3.5.6 1.4 1.4.6-1.4.6-.6 1.4-.6-1.4-1.4-.6 1.4-.6.6-1.4Z" fill="currentColor"/></>,
  "music-note": <><path d="M8 15.5V5l7-1.5V13" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/><circle cx="6" cy="15.5" r="2" stroke="currentColor" strokeWidth="1.5"/><circle cx="13" cy="13" r="2" stroke="currentColor" strokeWidth="1.5"/></>,
  "newspaper": <><rect x="3" y="4" width="14" height="12" rx="1.8" stroke="currentColor" strokeWidth="1.5"/><path d="M6 7.5h4.5v3.5H6zM13 7.5h1M13 11h1M6 13.5h8" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"/></>,
  "pause": <><path d="M6 4.5h2.5v11H6zM11.5 4.5H14v11h-2.5z"/></>,
  "pencil": <><path d="m4 16 .8-3.2 8.8-8.8a1.4 1.4 0 0 1 2 0l.4.4a1.4 1.4 0 0 1 0 2l-8.8 8.8L4 16Z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"/><path d="m12.5 5.5 2 2" stroke="currentColor" strokeWidth="1.5"/></>,
  "people": <><circle cx="7.5" cy="7" r="2.6" stroke="currentColor" strokeWidth="1.5"/><path d="M2.5 16a5 5 0 0 1 10 0" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/><path d="M13 4.6a2.6 2.6 0 0 1 0 4.9M14.5 11.6a5 5 0 0 1 3 4.4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/></>,
  "person": <><circle cx="10" cy="6.5" r="3" stroke="currentColor" strokeWidth="1.5"/><path d="M4 16.5a6 6 0 0 1 12 0" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/></>,
  "photo": <><rect x="3.5" y="4.5" width="13" height="11" rx="2" stroke="currentColor" strokeWidth="1.5"/><circle cx="7.5" cy="8" r="1.2" fill="currentColor"/><path d="m5 14 3.5-3.5 2 2L14 9l2.5 3" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></>,
  "pin": <><path d="M10 17s-5-4.3-5-8a5 5 0 0 1 10 0c0 3.7-5 8-5 8Z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"/><circle cx="10" cy="9" r="1.8" stroke="currentColor" strokeWidth="1.5"/></>,
  "play": <><path d="M7 4.9v10.2a.6.6 0 0 0 .92.5l8-5.1a.6.6 0 0 0 0-1l-8-5.1a.6.6 0 0 0-.92.5Z"/></>,
  "plus": <><path d="M10 4v12M4 10h12" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/></>,
  "refresh": <><path d="M15.8 10A5.8 5.8 0 1 1 13 5.1M15.8 3.5v3.2h-3.2" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></>,
  "repeat": <><path d="M5.5 8V7A2.5 2.5 0 0 1 8 4.5h6.5M12.5 2.5l2 2-2 2M14.5 12v1a2.5 2.5 0 0 1-2.5 2.5H5.5M7.5 17.5l-2-2 2-2" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></>,
  "search": <><circle cx="9" cy="9" r="5.5" stroke="currentColor" strokeWidth="1.5"/><path d="m13.5 13.5 3 3" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/></>,
  "send": <><path d="m3.5 10 13-6-3.5 13-3.5-4.5L3.5 10Zm6 2.5L13 7" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"/></>,
  "share": <><path d="M10 12.5v-9M7 6l3-2.8L13 6" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/><path d="M5.5 9.5H5A1.5 1.5 0 0 0 3.5 11v4A1.5 1.5 0 0 0 5 16.5h10a1.5 1.5 0 0 0 1.5-1.5v-4A1.5 1.5 0 0 0 15 9.5h-.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/></>,
  "shield": <><path d="M10 3l6 2v5c0 3.5-2.5 5.8-6 7-3.5-1.2-6-3.5-6-7V5l6-2Z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"/><path d="m7.5 10 1.8 1.8L13 8.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></>,
  "sliders": <><path d="M3.5 6.5h5M12 6.5h4.5M3.5 13.5h3M10 13.5h6.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/><circle cx="10.2" cy="6.5" r="1.8" stroke="currentColor" strokeWidth="1.5"/><circle cx="8.2" cy="13.5" r="1.8" stroke="currentColor" strokeWidth="1.5"/></>,
  "sparkles": <><path d="M10 3l1.2 3.3 3.3 1.2-3.3 1.2L10 12 8.8 8.7 5.5 7.5l3.3-1.2L10 3Z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"/><path d="m14.8 11.5.7 1.8 1.8.7-1.8.7-.7 1.8-.7-1.8-1.8-.7 1.8-.7.7-1.8Z" stroke="currentColor" strokeWidth="1.3" strokeLinejoin="round"/></>,
  "speaker": <><path d="M4 8v4h2.5L10 15V5L6.5 8H4Z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"/><path d="M12.5 7.5a3.5 3.5 0 0 1 0 5M14.5 5.5a6 6 0 0 1 0 9" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/></>,
  "star": <><path d="m10 3 2 4.4 4.8.5-3.6 3.2 1 4.7L10 13.4l-4.2 2.4 1-4.7L3.2 7.9 8 7.4 10 3Z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"/></>,
  "sun": <><circle cx="10" cy="10" r="4" stroke="currentColor" strokeWidth="1.5"/><path d="M10 1.5v2m0 13v2M18.5 10h-2m-13 0h-2m14.5-6-1.4 1.4M4.9 15.1 3.5 16.5m0-13 1.4 1.4m10.2 10.2 1.4 1.4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/></>,
  "trash": <><path d="M4 6h12M8 6V4.5h4V6M6.5 6l.5 10h6l.5-10M8.5 9v4M11.5 9v4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></>,
  "warning": <><path d="M10 3.5 18 17H2L10 3.5Z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"/><path d="M10 8.5V12M10 14.5h.01" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/></>,
  "waveform": <><path d="M4 8.5v3M7 6v8M10 4v12M13 6.5v7M16 8.5v3" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/></>,
  "wifi": <><path d="M2.5 8a11 11 0 0 1 15 0M5 11a7.3 7.3 0 0 1 10 0M7.6 13.8a3.6 3.6 0 0 1 4.8 0" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/><circle cx="10" cy="16.2" r="1.1" fill="currentColor"/></>,
};

export interface IconProps extends Omit<SVGProps<SVGSVGElement>, "name"> {
  name: IconName;
  /** Matches the .b-icon size scale. */
  size?: "sm" | "md" | "lg" | "xl";
  /** Give the icon a label when it carries meaning on its own. */
  title?: string;
}

/**
 * A glyph from the Barua icon library: 20x20, 1.5px stroke, currentColor.
 * Decorative by default — pass `title` when the icon is the only label.
 */
export const Icon = forwardRef<SVGSVGElement, IconProps>(function Icon(
  { name, size, title, className, ...rest },
  ref
) {
  const glyph = GLYPHS[name];
  if (!glyph) return null;
  return (
    <svg
      ref={ref}
      className={cn("b-icon", size && size !== "md" && `b-icon--${size}`, className)}
      viewBox="0 0 20 20"
      fill="none"
      role={title ? "img" : undefined}
      aria-hidden={title ? undefined : true}
      {...rest}
    >
      {title ? <title>{title}</title> : null}
      {glyph}
    </svg>
  );
});
