#!/usr/bin/env python3
"""Generate packages/react/src/icon.tsx from docs/icons.html.

The icon library lives in the documentation — that is the copy people read and
propose additions to. Generating the React component from it means the two can
never drift: add a glyph to the docs, re-run this, and the component knows it.
"""
import re, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
html = (ROOT / "docs/icons.html").read_text()

# JSX needs camelCase for every hyphenated SVG attribute.
ATTRS = {
    "stroke-width": "strokeWidth", "stroke-linecap": "strokeLinecap",
    "stroke-linejoin": "strokeLinejoin", "stroke-dasharray": "strokeDasharray",
    "stroke-dashoffset": "strokeDashoffset", "fill-rule": "fillRule",
    "clip-rule": "clipRule", "fill-opacity": "fillOpacity",
    "stroke-opacity": "strokeOpacity", "stroke-miterlimit": "strokeMiterlimit",
}

def to_jsx(markup: str) -> str:
    for a, b in ATTRS.items():
        markup = markup.replace(a + "=", b + "=")
    return re.sub(r"\s+", " ", markup).strip()

glyphs = {}
for m in re.finditer(r'data-icon="([a-z0-9-]+)"><svg[^>]*>(.*?)</svg>', html, re.S):
    glyphs[m.group(1)] = to_jsx(m.group(2))

if not glyphs:
    raise SystemExit("no glyphs found — has docs/icons.html changed shape?")

lines = [
    '"use client";',
    "",
    "/* Generated by tools/build-react-icons.py from docs/icons.html — do not edit.",
    f"   {len(glyphs)} glyphs. To add one, put it in the docs first and re-run the script. */",
    "",
    'import { forwardRef, type SVGProps } from "react";',
    'import { cn } from "./cn";',
    "",
    "export const iconNames = [",
]
for name in sorted(glyphs):
    lines.append(f'  "{name}",')
lines += [
    "] as const;",
    "",
    "export type IconName = (typeof iconNames)[number];",
    "",
    "const GLYPHS: Record<IconName, JSX.Element> = {",
]
for name in sorted(glyphs):
    lines.append(f'  "{name}": <>{glyphs[name]}</>,')
lines += [
    "};",
    "",
    "export interface IconProps extends Omit<SVGProps<SVGSVGElement>, \"name\"> {",
    "  name: IconName;",
    "  /** Matches the .b-icon size scale. */",
    '  size?: "sm" | "md" | "lg" | "xl";',
    "  /** Give the icon a label when it carries meaning on its own. */",
    "  title?: string;",
    "}",
    "",
    "/**",
    " * A glyph from the Barua icon library: 20x20, 1.5px stroke, currentColor.",
    " * Decorative by default — pass `title` when the icon is the only label.",
    " */",
    "export const Icon = forwardRef<SVGSVGElement, IconProps>(function Icon(",
    "  { name, size, title, className, ...rest },",
    "  ref",
    ") {",
    "  const glyph = GLYPHS[name];",
    "  if (!glyph) return null;",
    "  return (",
    "    <svg",
    "      ref={ref}",
    '      className={cn("b-icon", size && size !== "md" && `b-icon--${size}`, className)}',
    '      viewBox="0 0 20 20"',
    '      fill="none"',
    "      role={title ? \"img\" : undefined}",
    "      aria-hidden={title ? undefined : true}",
    "      {...rest}",
    "    >",
    "      {title ? <title>{title}</title> : null}",
    "      {glyph}",
    "    </svg>",
    "  );",
    "});",
    "",
]
out = ROOT / "packages/react/src/icon.tsx"
out.write_text("\n".join(lines))
print(f"icon.tsx: {len(glyphs)} glyphs from docs/icons.html")
