import { chromium } from "playwright-core";
const [email, password, domainName] = process.argv.slice(2);
const browser = await chromium.launch({ channel: "chrome", headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 1000 } });
page.on("console", (m) => { if (m.type() === "error") console.log("  console:", m.text().slice(0, 160)); });
await page.goto("https://barua.tz/login", { waitUntil: "networkidle" });
await page.waitForTimeout(1500);
await page.fill('input[name="email"]', email);
await page.fill('input[name="password"]', password);
await page.locator('form button[type="submit"]').first().click();
await page.waitForURL((u) => !u.pathname.startsWith("/login"), { timeout: 30000 });
console.log("after login:", new URL(page.url()).pathname);
await page.goto("https://barua.tz/setup", { waitUntil: "networkidle" });
await page.waitForTimeout(1500);
const b = page.getByRole("button", { name: /not now|don.t ask again/i }).first();
if (await b.isVisible().catch(() => false)) await b.click().catch(() => {});
await page.fill("#businessName", "Trial Check Ltd");
await page.fill("#domainName", domainName);
await page.fill("#localPart", "info");
await page.locator('form button[type="submit"]').first().click();
await page.waitForTimeout(6000);
console.log("now at:", new URL(page.url()).pathname);
const txt = (await page.locator("body").innerText()).replace(/\s+/g, " ");
console.log("page says:", txt.slice(0, 400));
await page.screenshot({ path: "/tmp/setup-debug.png", fullPage: true });
await browser.close();
